import java.time.LocalDate;

/**
 * Represents a Sale transaction in the Sales Management System.
 * This POJO links a Product and a Customer.
 */
public class Sale {
    private int saleId;
    private int productId;
    private int customerId;
    private int quantity;
    private double unitPriceAtSale; // Price of the product at the time of sale
    private double totalSalePrice; // Calculated total price for this sale
    private LocalDate saleDate;

    // Constructor for creating new Sale objects (ID and total price will be generated by DAO)
    public Sale(int productId, int customerId, int quantity, double unitPriceAtSale, LocalDate saleDate) {
        this.productId = productId;
        this.customerId = customerId;
        this.quantity = quantity;
        this.unitPriceAtSale = unitPriceAtSale;
        this.saleDate = saleDate;
        this.totalSalePrice = unitPriceAtSale * quantity; // Initial calculation
    }

    // Constructor for retrieving Sale objects from the database (with all fields)
    public Sale(int saleId, int productId, int customerId, int quantity, double unitPriceAtSale, double totalSalePrice, LocalDate saleDate) {
        this.saleId = saleId;
        this.productId = productId;
        this.customerId = customerId;
        this.quantity = quantity;
        this.unitPriceAtSale = unitPriceAtSale;
        this.totalSalePrice = totalSalePrice;
        this.saleDate = saleDate;
    }

    // Getters
    public int getSaleId() {
        return saleId;
    }

    public int getProductId() {
        return productId;
    }

    public int getCustomerId() {
        return customerId;
    }

    public int getQuantity() {
        return quantity;
    }

    public double getUnitPriceAtSale() {
        return unitPriceAtSale;
    }

    public double getTotalSalePrice() {
        return totalSalePrice;
    }

    public LocalDate getSaleDate() {
        return saleDate;
    }

    // Setters
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
        this.totalSalePrice = this.unitPriceAtSale * this.quantity; // Recalculate total
    }

    public void setUnitPriceAtSale(double unitPriceAtSale) {
        this.unitPriceAtSale = unitPriceAtSale;
        this.totalSalePrice = this.unitPriceAtSale * this.quantity; // Recalculate total
    }

    public void setTotalSalePrice(double totalSalePrice) {
        this.totalSalePrice = totalSalePrice;
    }

    public void setSaleDate(LocalDate saleDate) {
        this.saleDate = saleDate;
    }

    @Override
    public String toString() {
        return "Sale{" +
                "saleId=" + saleId +
                ", productId=" + productId +
                ", customerId=" + customerId +
                ", quantity=" + quantity +
                ", unitPriceAtSale=" + unitPriceAtSale +
                ", totalSalePrice=" + totalSalePrice +
                ", saleDate=" + saleDate +
                '}';
    }
}
